<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'name' => 'The Wilbert Bronze',
                'sku' => 'W3086-B',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Bronze Triune',
                'sku' => 'W3086-BT',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Copper Triune',
                'sku' => 'W3086-CT',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Stainless Steel Triune',
                'sku' => 'W3086-SST',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Cameo Rose Triune',
                'sku' => 'W3086-CAM',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Veteran Triune',
                'sku' => 'W3086-VT',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Venetian',
                'sku' => 'W3086-V',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Continental',
                'sku' => 'W3086-C',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Salute',
                'sku' => 'W3086-S',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Monticello (standard)',
                'sku' => 'W3086-M',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Monticello (oversized)',
                'sku' => 'W3490-M',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Monticello (youth)',
                'sku' => 'W2056-M',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Bronze Triune Urn Vault',
                'sku' => 'UV1212-BT',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Copper Triune Urn Vault',
                'sku' => 'UV1212-CT',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Stainless Steel Triune Urn Vault',
                'sku' => 'UV1212-SST',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Cameo Rose Triune Urn Vault',
                'sku' => 'UV1212-CAM',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Veteran Triune Urn Vault',
                'sku' => 'UV1212-VT',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Venetian Urn Vault',
                'sku' => 'UV1212-V',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'White Venetian Urn Vault',
                'sku' => 'UV1212-WVS',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Monticello Urn Vault',
                'sku' => 'UV1212-M',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Venetian (short) Urn Vault',
                'sku' => 'UV712-VS',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'White Venetian (short) Urn Vault',
                'sku' => 'UV712-WVS',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Monticello (short) Urn Vault',
                'sku' => 'UV712-MS',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Ring Liner (standard)',
                'sku' => 'L3086-4',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Ring Liner (24" x 72")',
                'sku' => 'L2472-4',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Ring Liner (24" x 56")',
                'sku' => 'L2456-4',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Ring Liner (18" x 49")',
                'sku' => 'L1849-4',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Ring Liner (16" x 37")',
                'sku' => 'L1637-4',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Ring Liner (14" x 31")',
                'sku' => 'L1431-4',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Ring Liner (12" x 26")',
                'sku' => 'L1226-4',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Christy Vault (standard)',
                'sku' => 'V3086-1',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Christy Vault (oversize)',
                'sku' => 'V3290-1',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Christy Vault (24" x 64")',
                'sku' => 'V2464-1',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Christy Vault (18" x 48")',
                'sku' => 'V1848-1',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Christy Vault (16" x 37")',
                'sku' => 'V1637-1',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Single Garden Crypt (standard)',
                'sku' => 'G3086-6',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Single Garden Crypt (oversize)',
                'sku' => 'G3690-6',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Single Garden Crypt (28" x 84")',
                'sku' => 'G2884-6',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Single Garden Crypt (grande)',
                'sku' => 'G4490-G',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Companion Garden Crypt (standard)',
                'sku' => 'G3086-5',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Companion Garden Crypt (straight wall)',
                'sku' => 'G3086-4',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Cover (standard)',
                'sku' => '2-3086G5',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Cover (oversize)',
                'sku' => '2-3690G5',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Straight Wall Ring (standard)',
                'sku' => '3-3086G4',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Companion Garden Crypt Base (standard)',
                'sku' => '1-3086G5',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Inner Shutter (standard)',
                'sku' => '4-3086G5',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            // bronze markers
            [
                'name' => 'Bronze Marker',
                'sku' => 'B2211NV',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Bronze Marker (oversize)',
                'sku' => 'B2413NV',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Bronze Marker',
                'sku' => 'B2414NV',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Bronze Marker',
                'sku' => 'B3613V1-6',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Bronze Marker',
                'sku' => 'B2412V1-5SL',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Bronze Marker',
                'sku' => 'B2416V1-6',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Bronze Marker',
                'sku' => 'B2412V2-3.75',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Bronze Marker',
                'sku' => 'B2412V2-4',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Bronze Marker',
                'sku' => 'B2816V2-4',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Bronze Marker',
                'sku' => 'B2412V1-4',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Bronze Marker',
                'sku' => 'B2412V1-5',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Bronze Marker',
                'sku' => 'B2816V1-4',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Granite Marker',
                'sku' => 'G1814V2-3.75',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Granite Marker',
                'sku' => 'G2412V2-4',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Granite Marker',
                'sku' => 'G2412V2-3.75',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Granite Marker',
                'sku' => 'G2412V2-3.75 (deep)',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Granite Marker',
                'sku' => 'G1814SV2-3.75',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Granite Marker',
                'sku' => 'G2412NV',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Granite Marker',
                'sku' => 'G2816NV',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Granite Marker',
                'sku' => 'G2412SV-4',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Granite Marker',
                'sku' => 'G1810V1-4',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Granite Marker',
                'sku' => 'G2412V1-5',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Granite Marker',
                'sku' => 'G2412V1-4',
                'price' => 0,
                'stock' => 0,
                'is_active' => true,
            ],

            // Add more products as needed
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
