version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: christyvault-app
        container_name: christyvault-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        expose:
            - "9000"
        environment:
            - APP_ENV=production
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=christyvault
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres
        depends_on:
            - db

    db:
        image: postgres:17
        container_name: christyvault-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: christyvault
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
            - ./docker/postgres/init-postgis.sh:/docker-entrypoint-initdb.d/init-postgis.sh

    queue:
        build:
            context: .
        container_name: christyvault-queue
        restart: unless-stopped
        working_dir: /var/www
        command: php artisan queue:work --tries=3
        volumes:
            - ./:/var/www
        depends_on:
            - app
        environment:
            - APP_ENV=production
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=christyvault
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres

volumes:
    db_data:
