services:
    init:
        image: christyvault-app
        container_name: christyvault-init
        working_dir: /var/www
        depends_on:
            - db
        command: sh -c "php artisan migrate --force"
        volumes:
            - ./storage:/var/www/storage
            - ./.env:/var/www/.env
        environment:
            - APP_ENV=production
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=christyvault
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres

    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: christyvault-app
        container_name: christyvault-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./storage:/var/www/storage
            - ./.env:/var/www/.env
        command: php-fpm
        expose:
            - "8000"
        depends_on:
            - db
            - init
        environment:
            - APP_ENV=production
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=christyvault
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres

    queue:
        image: christyvault-app
        container_name: christyvault-queue
        restart: unless-stopped
        working_dir: /var/www
        command: php artisan queue:work --tries=3
        volumes:
            - ./storage:/var/www/storage
            - ./.env:/var/www/.env
        depends_on:
            - db
            - init
        environment:
            - APP_ENV=production
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=christyvault
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres

    db:
        image: postgres:17
        container_name: christyvault-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: christyvault
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
            - ./docker/postgres/init-postgis.sh:/docker-entrypoint-initdb.d/init-postgis.sh

volumes:
    db_data:
